// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: vm.proto

package vyomav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	VmService_CreateVm_FullMethodName        = "/vyoma.v1.VmService/CreateVm"
	VmService_StartVm_FullMethodName         = "/vyoma.v1.VmService/StartVm"
	VmService_StopVm_FullMethodName          = "/vyoma.v1.VmService/StopVm"
	VmService_DeleteVm_FullMethodName        = "/vyoma.v1.VmService/DeleteVm"
	VmService_ListVms_FullMethodName         = "/vyoma.v1.VmService/ListVms"
	VmService_GetVm_FullMethodName           = "/vyoma.v1.VmService/GetVm"
	VmService_ExecCommand_FullMethodName     = "/vyoma.v1.VmService/ExecCommand"
	VmService_StreamLogs_FullMethodName      = "/vyoma.v1.VmService/StreamLogs"
	VmService_CreateSnapshot_FullMethodName  = "/vyoma.v1.VmService/CreateSnapshot"
	VmService_RestoreSnapshot_FullMethodName = "/vyoma.v1.VmService/RestoreSnapshot"
	VmService_MigrateVm_FullMethodName       = "/vyoma.v1.VmService/MigrateVm"
)

// VmServiceClient is the client API for VmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VmServiceClient interface {
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error)
	StartVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmStatusResponse, error)
	StopVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmStatusResponse, error)
	DeleteVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error)
	GetVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmInfo, error)
	ExecCommand(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (VmService_ExecCommandClient, error)
	StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (VmService_StreamLogsClient, error)
	CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotInfo, error)
	RestoreSnapshot(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*VmInfo, error)
	MigrateVm(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (VmService_MigrateVmClient, error)
}

type vmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVmServiceClient(cc grpc.ClientConnInterface) VmServiceClient {
	return &vmServiceClient{cc}
}

func (c *vmServiceClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVmResponse)
	err := c.cc.Invoke(ctx, VmService_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) StartVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmStatusResponse)
	err := c.cc.Invoke(ctx, VmService_StartVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) StopVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmStatusResponse)
	err := c.cc.Invoke(ctx, VmService_StopVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) DeleteVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VmService_DeleteVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVmsResponse)
	err := c.cc.Invoke(ctx, VmService_ListVms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) GetVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmInfo)
	err := c.cc.Invoke(ctx, VmService_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) ExecCommand(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (VmService_ExecCommandClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VmService_ServiceDesc.Streams[0], VmService_ExecCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &vmServiceExecCommandClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VmService_ExecCommandClient interface {
	Recv() (*ExecOutput, error)
	grpc.ClientStream
}

type vmServiceExecCommandClient struct {
	grpc.ClientStream
}

func (x *vmServiceExecCommandClient) Recv() (*ExecOutput, error) {
	m := new(ExecOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vmServiceClient) StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (VmService_StreamLogsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VmService_ServiceDesc.Streams[1], VmService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &vmServiceStreamLogsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VmService_StreamLogsClient interface {
	Recv() (*LogLine, error)
	grpc.ClientStream
}

type vmServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *vmServiceStreamLogsClient) Recv() (*LogLine, error) {
	m := new(LogLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vmServiceClient) CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotInfo)
	err := c.cc.Invoke(ctx, VmService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) RestoreSnapshot(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*VmInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmInfo)
	err := c.cc.Invoke(ctx, VmService_RestoreSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) MigrateVm(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (VmService_MigrateVmClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VmService_ServiceDesc.Streams[2], VmService_MigrateVm_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &vmServiceMigrateVmClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VmService_MigrateVmClient interface {
	Recv() (*MigrationProgress, error)
	grpc.ClientStream
}

type vmServiceMigrateVmClient struct {
	grpc.ClientStream
}

func (x *vmServiceMigrateVmClient) Recv() (*MigrationProgress, error) {
	m := new(MigrationProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VmServiceServer is the server API for VmService service.
// All implementations must embed UnimplementedVmServiceServer
// for forward compatibility
type VmServiceServer interface {
	CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error)
	StartVm(context.Context, *VmIdRequest) (*VmStatusResponse, error)
	StopVm(context.Context, *VmIdRequest) (*VmStatusResponse, error)
	DeleteVm(context.Context, *VmIdRequest) (*emptypb.Empty, error)
	ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error)
	GetVm(context.Context, *VmIdRequest) (*VmInfo, error)
	ExecCommand(*ExecRequest, VmService_ExecCommandServer) error
	StreamLogs(*LogRequest, VmService_StreamLogsServer) error
	CreateSnapshot(context.Context, *SnapshotRequest) (*SnapshotInfo, error)
	RestoreSnapshot(context.Context, *RestoreRequest) (*VmInfo, error)
	MigrateVm(*MigrateRequest, VmService_MigrateVmServer) error
	mustEmbedUnimplementedVmServiceServer()
}

// UnimplementedVmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVmServiceServer struct {
}

func (UnimplementedVmServiceServer) CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedVmServiceServer) StartVm(context.Context, *VmIdRequest) (*VmStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVm not implemented")
}
func (UnimplementedVmServiceServer) StopVm(context.Context, *VmIdRequest) (*VmStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVm not implemented")
}
func (UnimplementedVmServiceServer) DeleteVm(context.Context, *VmIdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVm not implemented")
}
func (UnimplementedVmServiceServer) ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVms not implemented")
}
func (UnimplementedVmServiceServer) GetVm(context.Context, *VmIdRequest) (*VmInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedVmServiceServer) ExecCommand(*ExecRequest, VmService_ExecCommandServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedVmServiceServer) StreamLogs(*LogRequest, VmService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedVmServiceServer) CreateSnapshot(context.Context, *SnapshotRequest) (*SnapshotInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedVmServiceServer) RestoreSnapshot(context.Context, *RestoreRequest) (*VmInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedVmServiceServer) MigrateVm(*MigrateRequest, VmService_MigrateVmServer) error {
	return status.Errorf(codes.Unimplemented, "method MigrateVm not implemented")
}
func (UnimplementedVmServiceServer) mustEmbedUnimplementedVmServiceServer() {}

// UnsafeVmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VmServiceServer will
// result in compilation errors.
type UnsafeVmServiceServer interface {
	mustEmbedUnimplementedVmServiceServer()
}

func RegisterVmServiceServer(s grpc.ServiceRegistrar, srv VmServiceServer) {
	s.RegisterService(&VmService_ServiceDesc, srv)
}

func _VmService_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_StartVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).StartVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_StartVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).StartVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_StopVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).StopVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_StopVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).StopVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_DeleteVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).DeleteVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_DeleteVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).DeleteVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_ListVms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).ListVms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_ListVms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).ListVms(ctx, req.(*ListVmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).GetVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_ExecCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VmServiceServer).ExecCommand(m, &vmServiceExecCommandServer{ServerStream: stream})
}

type VmService_ExecCommandServer interface {
	Send(*ExecOutput) error
	grpc.ServerStream
}

type vmServiceExecCommandServer struct {
	grpc.ServerStream
}

func (x *vmServiceExecCommandServer) Send(m *ExecOutput) error {
	return x.ServerStream.SendMsg(m)
}

func _VmService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VmServiceServer).StreamLogs(m, &vmServiceStreamLogsServer{ServerStream: stream})
}

type VmService_StreamLogsServer interface {
	Send(*LogLine) error
	grpc.ServerStream
}

type vmServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *vmServiceStreamLogsServer) Send(m *LogLine) error {
	return x.ServerStream.SendMsg(m)
}

func _VmService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).CreateSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_RestoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).RestoreSnapshot(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_MigrateVm_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MigrateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VmServiceServer).MigrateVm(m, &vmServiceMigrateVmServer{ServerStream: stream})
}

type VmService_MigrateVmServer interface {
	Send(*MigrationProgress) error
	grpc.ServerStream
}

type vmServiceMigrateVmServer struct {
	grpc.ServerStream
}

func (x *vmServiceMigrateVmServer) Send(m *MigrationProgress) error {
	return x.ServerStream.SendMsg(m)
}

// VmService_ServiceDesc is the grpc.ServiceDesc for VmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vyoma.v1.VmService",
	HandlerType: (*VmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVm",
			Handler:    _VmService_CreateVm_Handler,
		},
		{
			MethodName: "StartVm",
			Handler:    _VmService_StartVm_Handler,
		},
		{
			MethodName: "StopVm",
			Handler:    _VmService_StopVm_Handler,
		},
		{
			MethodName: "DeleteVm",
			Handler:    _VmService_DeleteVm_Handler,
		},
		{
			MethodName: "ListVms",
			Handler:    _VmService_ListVms_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _VmService_GetVm_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _VmService_CreateSnapshot_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _VmService_RestoreSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecCommand",
			Handler:       _VmService_ExecCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _VmService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MigrateVm",
			Handler:       _VmService_MigrateVm_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vm.proto",
}
